api/urls.py
# -*- coding: utf-8 -*-


from django.conf.urls import url, include
from . import views
from rest_framework.routers import DefaultRouter

from rest_framework_nested import routers

# Create a router and register our viewsets with it.
router = DefaultRouter()

router.register(r'events', views.EventsViewSet)
router.register(r'users', views.UsersViewSet)
router.register(r'places', views.PlacesViewSet)
router.register(r'collections', views.CollectionsViewSet)

router.register(r'search', views.SearchViewSet, base_name='search')
router.register(r'cities', views.CitiesViewSet)
router.register(r'categories', views.CategoriesViewSet)

collections_router = routers.NestedSimpleRouter(
    router,
    r'events',
    lookup='event'
)

collections_router.register(
    r'collections',
    views.CollectionActionsViewSet,
    base_name='event-collections'
)

collections_router.register(
    r'categories',
    views.CategoryActionsViewSet,
    base_name='event-categories'
)

# The API URLs are now determined automatically by the router.
# Additionally, we include the login URLs for the browsable API.
urlpatterns = [
    url(r'^auth/', include('api.auth.urls.authtoken')),
    url(r'^auth/devices/', include('api.auth.urls.devices')),
    url(r'^', include(router.urls)),
    url(r'^', include(collections_router.urls)),
]

app/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
import os
import hashlib

from django.db import models
from django.dispatch import receiver
from django.conf import settings

from django.contrib.auth.models import AbstractUser
from django.contrib.postgres.fields import JSONField
from django.contrib.postgres.search import SearchVectorField
from django.core.urlresolvers import reverse
from django.core.cache import cache

from django.core.cache.utils import make_template_fragment_key

from django.utils.translation import ugettext_lazy as _

from django.core.validators import MaxValueValidator, MinValueValidator

from cities.models import BaseCity, AlternativeName

from versatileimagefield.fields import VersatileImageField, PPOIField
from versatileimagefield.placeholder import OnStoragePlaceholderImage
from dry_rest_permissions.generics import authenticated_users

from pytils.translit import slugify as default_slugify
from autoslug import AutoSlugField

from services.elastic.managers import (
    EventIndexManager, CollectionIndexManager,
    PlaceIndexManager, CityIndexManager, VoteIndexManager,
    CategoryIndexManager
)

from . managers import EventManager, CollectionManager, ScheduleManager


def md5_slugify(name):
    name = default_slugify(name)
    hash_name = hashlib.md5(name.encode())
    return hash_name.hexdigest()


def get_image_dir(instance, filename):
    name, ext = os.path.splitext(filename)
    return 'events/%s%s' % (md5_slugify(name), ext)


def get_avatar_dir(instance, filename):
    name, ext = os.path.splitext(filename)
    return 'users/%s%s' % (md5_slugify(name), ext)


class User(AbstractUser):
    headshot = VersatileImageField(_('Headshot'),
                                   upload_to=get_avatar_dir,
                                   blank=True, null=True,
                                   placeholder_image=OnStoragePlaceholderImage(
                                       path='placeholders/userplaceholder.png'
                                   ),
                                   ppoi_field='headshot_ppoi')
    username = models.CharField(_('username'), max_length=200,
                                unique=True, blank=True, null=True)
    first_name = models.CharField(_('Name'), max_length=200,
                                  blank=True, null=True)
    last_name = models.CharField(_('Last name'), max_length=200,
                                 blank=True, null=True)
    business_account = models.BooleanField(_('Business account'),
                                           default=False)
    vk_profile = JSONField(_('Vk profile'), blank=True, null=True)
    fb_profile = JSONField(_('Fb profile'), blank=True, null=True)
    favorite_places = JSONField(_('Favorite places'), blank=True, null=True)
    short_bio = models.TextField(_('Short biography'),
                                 blank=True, null=True)
    headshot_ppoi = PPOIField()

    REQUIRED_FIELDS = ['email', 'first_name']

    def __str__(self):
        return "%s" % (self.email)

    class Meta:
        verbose_name = _('User')
        verbose_name_plural = _('Users')

    def admin_avatar(self):
        url = self.headshot.crop['50x50'].url
        return '<img src="%s">' % url

    admin_avatar.short_description = _('avatar')
    admin_avatar.allow_tags = True

    def profile_link(self):
        url = self.get_absolute_url()
        if self.first_name:
            result = '<a target="_blank" href="%s">%s</a>' % (
                url,
                self.first_name[:25])
            return result

    profile_link.short_description = _('Profile')
    profile_link.allow_tags = True

    @models.permalink
    def get_absolute_url(self):
        return ('profile-detail', None, {'pk': str(self.pk)})

    @staticmethod
    def has_read_permission(request):
        """ Allow to any user read User list.
        """
        return True

    @staticmethod
    @authenticated_users
    def has_write_permission(request):
        """ Disallow to create new users through api.
        """
        return False

    @staticmethod
    def has_object_read_permission(request):
        """ Allow to any user read User object.
        """
        return True

    @authenticated_users
    def has_object_write_permission(self, request):
        """ Allow update only self profile
        """
        return request.user == self

    @staticmethod
    @authenticated_users
    def has_profile_permission(request):
        """ Allow show self profile.
        """
        return True


class Subscriber(models.Model):
    email = models.EmailField(_('email'))
    event_id = models.CharField(_('Event ID'), max_length=200)
    event_title = models.CharField(_('Event title'),
                                   max_length=500,
                                   blank=True, null=True)
    event_slug = models.CharField(_('Event slug'),
                                  max_length=500,
                                  blank=True, null=True)
    date_added = models.DateTimeField(_(u'Date Added'),
                                      auto_now_add=True)

    def __str__(self):
        return "%s" % (self.email)

    class Meta:
        verbose_name = _('Subscriber')
        verbose_name_plural = _('Subscribers')


class Event(models.Model):
    title = models.CharField(_('Title'), max_length=200)
    slug = AutoSlugField(populate_from='title', unique=True)
    description = models.TextField(_('Description'), blank=True)

    video_url = models.URLField(_('Video URL'), max_length=200,
                                blank=True, null=True)

    vk_url = models.URLField(_('Vkontakte URL'),
                             max_length=1200,
                             blank=True,
                             null=True)

    fb_url = models.URLField(_('Facebook URL'),
                             max_length=1200,
                             blank=True,
                             null=True)

    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               related_name='events',
                               blank=True, null=True,
                               on_delete=models.CASCADE)

    collections = models.ManyToManyField('EventCollection',
                                         related_name='events',
                                         blank=True)
    place = models.ForeignKey('EventPlace',
                              verbose_name=_('Place'),
                              blank=True, null=True)
    category = models.CharField(_('Category'),
                                max_length=30,
                                blank=True, null=True)

    similar = JSONField(_('Similar events'), blank=True, null=True)
    ticket_price = models.CharField(_('Ticket price'),
                                    max_length=100,
                                    blank=True,
                                    null=True)
    ticket_url = models.URLField(_('Ticket URL'),
                                 blank=True, null=True)
    currency = models.CharField(_('Currency'),
                                max_length=200,
                                blank=True,
                                null=True)

    date_added = models.DateTimeField(_(u'Date Added'), auto_now_add=True)
    date_updated = models.DateTimeField(_(u'Date Updated'), auto_now=True)
    deleted = models.BooleanField(_('Mark as deleted'), default=False)

    provider = models.CharField(_('Provider'),
                                max_length=20,
                                blank=True, null=True)
    provider_id = models.BigIntegerField(_('Provider ID'),
                                         blank=True,
                                         null=True)
    provider_image = models.CharField(_('Provider Image'),
                                      max_length=400,
                                      blank=True, null=True)
    provider_images = JSONField(_('Provider Images'),
                                blank=True,
                                null=True)

    search = SearchVectorField(_('Search'),
                               blank=True,
                               null=True,
                               editable=False)

    objects = EventManager()
    index = EventIndexManager()

    def __str__(self):
        return "%s" % (self.title)

    class Meta:
        verbose_name = _('Event')
        verbose_name_plural = _('Events')
        permissions = (
            ('translate_event', _('Translate Event')),
        )

    def admin_thumbnail(self):
        try:
            image = self.images.first().image
            url = image.crop['100x100'].url
            return '<img src="%s">' % url
        except:
            return None

    admin_thumbnail.short_description = _('preview')
    admin_thumbnail.allow_tags = True

    @property
    def average_rate(self):
        """
        Get the averate rate for event.
        """
        return self.votes.aggregate(value=models.Avg('rating'))

    @property
    def voted_users(self):
        """
        Get users id that voted for event.
        """
        return self.votes.values_list('author', flat=True)

    @property
    def actual_schedule(self):
        """
        Get the current schedule, or the near future.
        """
        return self.schedules.actual().first() or self.schedules.future().first()

    @property
    def actual_start_date(self):
        """
        Get start_date for actual schedule or the first in the future.
        """
        schedule = self.actual_schedule or self.schedules.first()
        if schedule:
            return schedule.start_date

    @property
    def actual_end_date(self):
        """
        Get end_date for actual schedule or the first in the future.
        """
        schedule = self.actual_schedule or self.schedules.first()
        if schedule:
            return schedule.end_date

    @property
    def mainimage(self):

templates/components/add-to-category-widget-template.html
{% verbatim %}
<script type="text/x-template" id="add-to-category-widget-template">
<div id="add-to-collection-widget">
	<div class="top-section">
    <span class="caption">{{lang.add_to_category || 'Add to category'}}</span>
	</div>
	<div class="middle-section">
		{{#each categories as category}}
			<div class="collection-item {{selectedIDList.indexOf(category.id) >= 0 ? 'selected' : ''}}">
				<span on-click="@this.fire('select', event, category)" rel="tooltip-long-text" data-tooltip-title="{{category.title}}">{{category.title}}</span>
				<i class="spritesheet sprite-ico-checkon"></i>
			</div>

      {{#if category.subcategories.length}}
        <div class="category-tree" style="margin-left: 20px;">
        {{#each category.subcategories as child}}
          <div on-click="@this.fire('select', event, child)" class="collection-item {{selectedIDList.indexOf(child.id) >= 0 ? 'selected' : ''}}">
            <span rel="tooltip-long-text" data-tooltip-title="{{child.title}}">{{child.title}}</span>
            <i class="spritesheet sprite-ico-checkon"></i>
          </div>
        {{/each}}
        </div>
      {{/if}}

		{{/each}}
	</div>
	<div class="bottom-section">
    <a on-click="saveCategory" class="button h32 save disabled" href="#">{{lang.save}}</a>
    <a on-click="cancel" class="button transparent h32 cancel" href="#">{{lang.cancel}}</a>
	</div>
</div>
</script>
{% endverbatim %}

templates/components/add-to-collection-widget-template.html
{% verbatim %}
<script type="text/x-template" id="add-to-collection-widget-template">
<div id="add-to-collection-widget">
	<div class="top-section">
    <a class="caption-link" href="#" on-click="addNewCollection">{{lang.create_new_collection}}</a>
	</div>
	<div class="middle-section">
		{{#each user.collections as collection}}
			<div href="#" on-click="@this.fire('select', event, collection)" class="collection-item {{selectedIDList.indexOf(collection.id) >= 0 ? 'selected' : ''}}">
				<span rel="tooltip-long-text" data-tooltip-title="{{ collection.title }}">{{collection.title}}</span>
				<i class="spritesheet sprite-ico-checkon"></i>
			</div>
		{{/each}}
	</div>
	<div class="bottom-section">
    <a on-click="save" class="button h32 save disabled" href="#">{{lang.save}}</a>
    <a on-click="cancel" class="button transparent h32 cancel" href="#">{{lang.cancel}}</a>
	</div>
</div>
</script>
{% endverbatim %}

templates/components/add-to-event-widget-template.html
{% verbatim %}
<!-- template for the login modal component -->
<script type="text/x-template" id="add-to-event-widget-template">
  <!--<form on-submit="searchEvent" class="row search-events" id="add-to-event-widget">
    <input on-click="showDropdown" type="text"
      value="{{query}}"
      name="query"
      placeholder="{{lang.find_and_add_event_to_collection}}">
    <button on-click="searchEvent" type="submit">
    {{#if loading}}
      <i class="button-spinner"></i>
    {{else}}
      <i class="spritesheet sprite-icо-search"></i>
    {{/if}}
    </button>

    {{#if events}}
      <div class="autocomplete-holder">
        <ul>
          {{#each events:index}}
          <li class="caption">
            {{#if image}}
              <img on-click="@this.fire('showEventDetail', @context, index)"  src="{{image}}">
            {{else}}
              <img>
            {{/if}}
            <span on-click="@this.fire('showEventDetail', @context, index)" >
              {{ title }}<br>
              {{ place.city }} &bull; {{formatSchedule(_.last(schedules)).locale(locale).format('DD MMMM YYYY HH:mm')}}
            </span>
            {{#if .added}}
              <div class="add-event-action visible"><i class="spritesheet sprite-ico-check"></i></div>
            {{else}}
              <div on-click="@this.fire('addToCollection', @context, index)" class="add-event-action">
                {{#if .processing}}
                  <i class="button-spinner"></i>
                {{else}}
                  <i class="spritesheet sprite-ico-grey-ico-grey-add"></i>
                {{/if}}
              </div>
            {{/if}}
          </li>
          {{/each}}
          <li class="show-more" on-click="showMore">
            <a class="caption-link" href="#">{{lang.all_events_by_query}} &laquo;{{query}}&raquo;</a>
          </li>
        </ul>
      </div>
    {{/if}}
  </form>-->

  <div class="events-buckets">
    {{#each collection.facets.day_events as bucket}}
      {{#if bucket.doc_count}}
      <div class="row events-list {{isPastBucket(bucket.key) && showActual ? 'hide' : ''}}">
          <a class="date-col subtitle" on-click="scrollToMonth" href="#{{formatMonthNum(bucket.key)}}" data-month="{{formatMonthNum(bucket.key)}}">
            {{formatBucketTitle(bucket.key)}}
          </a>
          <div class="events-col">
            <ul class="large-block-grid-2 small-block-grid-1">
              {{#each bucket.events as event}}
                <li class="card card-event">
                  <a href="/events/{{event.provider_id}}-{{event.slug}}/">
                    <div class="card-image">
                        {{#if image }}
                          <div class="card-img" style="background-image: url({{ image }})"></div>
                        {{/if}}
                      <div class="card-actions">
                        <span class="card-star">{{formatAverateRate(average_rate) || 0}}&nbsp;<i class="spritesheet sprite-ico-small-star"></i></span>
                      </div>
                    </div>
                    <div class="card-section">
                      <div class="title">
                        {{#if event.title_localized}}
                          {{ formatFirstLetter(event.title_localized[locale] || event.title) }}
                        {{else}}
                          {{ formatFirstLetter(event.title) }}
                        {{/if}}
                      </div>
                      <div class="subtitle">
                      {{event.place.city}} &bull; {{ formatSchedule(event.actual_schedule).locale(locale).format('DD MMMM YYYY') }} {{event.actual_schedule.start_time}}
                      </div>
                    </div>
                  </a>

                  {{#if collection.author.id == user.id || user.is_staff}}
                    {{#if collection.events.indexOf(id) >= 0}}
                    <div class="card-remove-button" on-click="@this.fire('removeFromCollection', event, id)">
                      <span class="card-icon"><i class="spritesheet sprite-ico-colored-close"></i></span>
                    </div>
                    {{/if}}
                  {{/if}}
                </li>
              {{/each}}
            </ul>
          </div>
        </div>
      {{/if}}
    {{/each}}
  </div>
</script>
{% endverbatim %}

templates/components/category-widget-template.html
{% verbatim %}
<!-- template for the login modal component -->
<script type="text/x-template" id="category-widget-template">

  <div class="row event-categories">
    {{#if events}}
      <h2>Found: {{events_total}}</h2>
    {{else}}
      <h2>Not found events</h2>
    {{/if}}
    {{#with params}}
    <p class="subtitle">{{#if query}}{{query}}{{/if}} {{#if city_name}}City: &laquo;{{city_name}}&raquo;{{/if}}</p>
    {{#if start_date || end_date}}
      <p class="subtitle">
        Dates: {{start_date}} {{end_date}}
      </p>
    {{/if}}
    {{/with}}
  </div>

  <div class="collection-detail row">
    <!-- Place details -->

    <div class="row">
    <!-- TODO common tempate for place card event_detail.html -->
      <div class="container event-map-container">
        <div class="row event-categories" style="width: 50%; float:left;">
          {{#each categories as category}}
          <a on-click="['selected', category]" style="margin:0 10px 10px 0;" href="#" class="button h32 {{selected.indexOf(category.key) != -1 ? 'orange' : ''}}">{{category.key}} ({{category.doc_count}})</a>
          {{/each}}
          {{#if lat && lng && getDistance}}
            <div class="row event-categories" style="margin: 40px 0 40px;">
            {{#if loading}}
              <button class="button disabled" disabled>Observing events... </button>&nbsp;
              <i class="spritesheet button-spinner"></i>&nbsp;
              <br>
              <span>center: <b>({{lat}}, {{lng}})</b>; radius:<b>({{parseInt(getDistance)}}m)</b></span>
            {{else}}
              <button class="button" on-click="observe_events">Observe events from provider</button>
              <br>
              <span>center: <b>({{lat}}, {{lng}})</b>; distance:<b>({{parseInt(getDistance)}}m)</b></span>
            {{/if}}
            </div>
          {{/if}}

        </div>
        <div style="height: 500px; width: 500px; float: left;"
                id="event-map"
                data-title="{{ place.title }}"
                data-lat="{{location.latitude}}"
                data-lng="{{location.longitude}}">
        </div>
      </div>
      <div class="clearfix pseudo-map-container is-last-block"></div>
    </div>
  </div>

  <div class="events-in-collection">

    <div class="row event-categories">
      {{#if events}}
        <h2>Found: {{events_total}}</h2>
      {{else}}
        <h2>Not found events</h2>
      {{/if}}
      {{#with params}}
      <p class="subtitle">{{#if query}}{{query}}{{/if}} {{#if city_name}}City: &laquo;{{city_name}}&raquo;{{/if}}</p>
      {{#if start_date || end_date}}
        <p class="subtitle">
          Dates: {{start_date}} {{end_date}}
        </p>
      {{/if}}
      {{/with}}
    </div>

    <div class="row event-categories">
      {{#each categories as category}}
      <a on-click="['selected', category]" style="margin:0 10px 10px 0;" href="#" class="button h32 {{selected.indexOf(category.key) != -1 ? 'orange' : ''}}">{{category.key}} ({{category.doc_count}})</a>
      {{/each}}
    </div>

    <div class="events-buckets" id="search-page">
      {{#if has_prev || has_next}}
        <li class="row pagination clearfix" style="width:100%;padding-bottom: 20px;">
          <div class="event-pagination body">
            {{#if has_prev}}
              <a on-click="prev_page" href="#" rel="page" class="endless_page_link">
                <i class="spritesheet sprite-ico-normal-prev"></i> Prev
              </a>
            {{else}}
              <span href="#" rel="page" class="endless_page_link" style="opacity: .1; text-decoration:none;">
                <i class="spritesheet sprite-ico-normal-prev"></i> Prev
              </span>
            {{/if}}
            <span class="endless_page_current">
              {{#if loading}}
                <i class="spritesheet button-spinner"></i>
              {{else}}
                <strong>{{current_page || 1}}</strong>
              {{/if}}
            </span>
            {{#if has_next}}
              <a on-click="next_page" href="#" rel="page" class="endless_page_link">
                Next <i class="spritesheet sprite-ico-normal-next"></i>
              </a>
            {{else}}
              <span href="#" rel="page" class="endless_page_link" style="opacity: .1; text-decoration:none;">
                Next <i class="spritesheet sprite-ico-normal-next"></i>
              </span>
            {{/if}}
          </div>
        </li>
      {{/if}}
      <ul class="large-block-grid-4 small-block-grid-1">
        {{#each events as event}}
          <li class="card card-event">
            <a href="/events/{{event.provider_id}}-{{event.slug}}/">
              <div class="card-image">
                  {{#if image }}
                    <div class="card-img" style="background-image: url({{ image }})"></div>
                  {{/if}}
                <div class="card-actions">
                  <span class="card-star">{{formatAverateRate(average_rate) || 0}}&nbsp;<i class="spritesheet sprite-ico-small-star"></i></span>
                </div>
              </div>
              <div class="card-section">
                <div class="title">
                  {{#if event.title_localized}}
                    {{ formatFirstLetter(event.title_localized[locale] || event.title) }}
                  {{else}}
                    {{ formatFirstLetter(event.title) }}
                  {{/if}}
                </div>
                <div class="subtitle">
                {{event.place.city}} ({{event.provider}}-{{event.rank}}) &bull; {{ formatSchedule(event.actual_schedule).locale(locale).format('DD MMMM YYYY') }} {{event.actual_schedule.start_time}}
                </div>
              </div>
            </a>

            {{#if collection.author.id == user.id || user.is_staff}}
              {{#if collection.events.indexOf(id) >= 0}}
              <div class="card-remove-button" on-click="@this.fire('removeFromCollection', event, id)">
                <span class="card-icon"><i class="spritesheet sprite-ico-colored-close"></i></span>
              </div>
              {{/if}}
            {{/if}}
          </li>
        {{/each}}
        <li class="row pagination clearfix" style="width:100%;">
          <div class="event-pagination body">
            <!--
            <span class="endless_page_current">
              <strong>1</strong>
            </span>
            -->
            {{#if has_prev}}
              <a on-click="prev_page" href="#" rel="page" class="endless_page_link">
                <i class="spritesheet sprite-ico-normal-prev"></i> Prev
              </a>
            {{else}}
              <span href="#" rel="page" class="endless_page_link" style="opacity: .1; text-decoration:none;">
                <i class="spritesheet sprite-ico-normal-prev"></i> Prev
              </span>
            {{/if}}
            <span class="endless_page_current">
              {{#if loading}}
                <i class="spritesheet button-spinner"></i>
              {{else}}
                <strong>{{current_page || 1}}</strong>
              {{/if}}
            </span>
            {{#if has_next}}
              <a on-click="next_page" href="#" rel="page" class="endless_page_link">
                Next <i class="spritesheet sprite-ico-normal-next"></i>
              </a>
            {{else}}
              <span href="#" rel="page" class="endless_page_link" style="opacity: .1; text-decoration:none;">
                Next <i class="spritesheet sprite-ico-normal-next"></i>
              </span>
            {{/if}}
          </div>
        </li>
      </ul>
    </div>
  </div>
</script>
{% endverbatim %}

templates/components/create-collection-modal.html
{% verbatim %}
<!-- template for the modal component -->
<script type="text/x-template" id="create-collection-modal-template">
  <div class="modal-mask {{showModal ? '' : 'hide'}}">
    <div class="modal-wrapper">
      <div class="modal-container create-collection-modal container">

        <div class="modal-header row">
          {{#if editCollection }}
            <h3>{{lang.edit_collection}}</h3>
          {{else}}
            <h3>{{lang.new_collection}}</h3>
          {{/if}}
        </div>

        <div class="modal-body">
          <form on-submit="save" class="event-form" action="" method="POST">

            <div class="row">
            <input class="u-full-width {{errors.title ? 'error' : ''}}" id="id_title" value="{{eventCollection.title}}" name="title" placeholder="{{lang.name_the_collection}}" type="text">
              {{#if errors.title}}
                {{#each errors.title as error}}
                  <span class="error error-text">{{error}}</span>
                {{/each}}
              {{/if}}
            </div>

            <!-- Photos -->

            <div class="row field photos">
              <p class="help-text caption">{{{lang.collection_image_cover}}}</p>
              <div as-dropzone="'collection'"
                data-keypath="eventCollection.images"
                class="event-images-wrapper {{eventCollection.images.length ? '' : 'empty'}}"></div>
            </div>

            <div class="row">
            <textarea value="{{eventCollection.description}}"
              class="u-full-width"
              cols="40" rows="10"
              id="id_description"
              name="description"
              placeholder="{{lang.what_is_this_collection_about}}">
                {{eventCollection.description}}
            </textarea>
            </div>

            <div class="row сonfidentiality-holder">
              <div class="сonfidentiality-item">
                <input {{eventCollection.private == 'false' ? 'checked' : ''}} id="id_public" name="{{eventCollection.private}}" value="false" type="radio">
                <label class="body" for="id_public">{{lang.public_visible_to_all}}</label>
              </div>
              <div class="сonfidentiality-item">
                <input  {{eventCollection.private == 'true' ? 'checked' : ''}} id="id_private" name="{{eventCollection.private}}" value="true" type="radio">
                <label class="body" for="id_private">{{lang.private_only_available_you}}</label>
              </div>
            </div>

            <div class="row сonfidentiality-holder">
              <div class="сonfidentiality-item">
                <input checked="{{eventCollection.limit_dates}}" id="id_limit_dates" type="checkbox">
                <label class="body" for="id_limit_dates">{{lang.limit_dates}}</label>
              </div>
              {{#if eventCollection.limit_dates}}
                <div class="dates-item five columns">
                  <input class="twelve columns"
                    id="id_limit_date_from"
                    as-datetimePicker="'limit_dates', 0"
                    value="{{eventCollection.limit_date_from}}"
                    name="event-schedule-start-date-0"
                    placeholder="{{lang.search_date_from}}">
                </div>
                <div class="dates-item one columns">&mdash;</div>
                <div class="dates-item five columns">
                  <input class="twelve columns"
                    id="id_limit_date_to"
                    as-datetimePicker="'limit_dates', 0"
                    value="{{eventCollection.limit_date_to}}"
                    name="event-schedule-end-date-0"
                    placeholder="{{lang.search_date_to}}">
                </div>
                <div class="twelve columns">
                  {{#if errors.limit_date_from}}
                    {{#each errors.limit_date_from as error}}
                      <span class="error error-text">{{error}}</span>
                    {{/each}}
                  {{/if}}
                  {{#if errors.limit_date_to}}
                    {{#each errors.limit_date_to as error}}
                      <span class="error error-text">{{error}}</span>
                    {{/each}}
                  {{/if}}
                </div>
              {{/if}}
            </div>
          </form>
        </div>

        <div class="modal-footer row">
          <button class="button" on-click="save">
            {{#if editCollection }}
              {{lang.save}}
            {{else}}
              {{lang.create}}
            {{/if}}
          </button>

          {{#if editCollection }}
          <button class="button orange" on-click="remove">
            {{lang.remove}}
          </button>
          {{/if}}

          <button class="button cancel-button" on-click="close">
            {{lang.cancel}}
          </button>
        </div>
      </div>
    </div>
  </div>
</script>
{% endverbatim %}

templates/components/remove-place-events-confirmation-modal.html
{% verbatim %}
<script type="text/x-template" id="remove-place-events-confirmation-modal-template">
    <div class="modal-mask {{showModal ? '' : 'hide'}}">
        <div class="modal-wrapper">
            <div class="modal-container remove-place-events-confirmation-modal">
                <a href="#" on-click="close" class="modal-close spritesheet sprite-ico-grey-close"></a>
                <h3>{{lang.attention}}</h3>
                <div class="body message">{{lang.remove_place_events_confirmation_modal_message}}</div>
                <hr>
                <div class="buttons-holder">
                    <a on-click="confirm" class="button red" href="#">{{lang.places_confirm_remove_button}}</a>
                    <a on-click="close" class="button transparent" href="#">{{lang.cancel}}</a>
                </div>
            </div>
        </div>
    </div>
</script>
{% endverbatim %}